language: python
python:
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"

# env variables
env:
  global:
    secure: "o+6mMab4m5uhwODm/i6UXdMkePh4m9bCXrK3HFLHT9YcUdAn0YnwES/rdh/bi2HMWOrtsbuUfVc6GKP/KETZSNIScXTNXHWk+G+ysmoKsJyFE9XtZzQgvZ7FwrfXuhpq6hnZmVf/+eMzU5P63Bp1HxsoZhsRc55Oh9M6uxyrmqXWL46rrC3+fp6g2WT1xdv7RZn3v2c2w/rpw0ZpFSGYSRfecE1mgIcR/YYp/wOJqmEAETgBtQzFHizRhcXnmDkJQRkezvLynaLZZ0F7Zvi4ziuDOroy4tLohm2ODAjS8K2OCK54IRRKK26V53sEsQwGhIgmGEiupO4Rt21eA5zhKoP1YFBl8/kMogwSaNbM8Fw/h0H0HCDpl+mfmwMxh4VOVgRpYn6tpcKxMIRrxRIBCzGXblTyqxkx8Fzf/MDKtn74DiZgsPg5uBdy2medXNuEz9Vi0JYt1QRmQzXWJ7PYu3msDEDoq4DbCBwV5ft9Bo5zHdiheNzEJlgIlD7aHYUp7sCb78UqeJus2ReM5hZyCGAXigJKWGOHhK0QCdbWwY1jcB2T8ldwuDBc0X3QL6iIbdvFrSa0TJ0cYX0RJizSO1h/co48ifmRUPu/v8j/lLee2CNhC08WbMLuMzct3+np9HwML4oQaxTX2sod1ou7xqRAFcpsSx4teEp7ybeQvsU="

# command to run tests
script:
  - export SAS_TOKEN=$SAS_TOKEN
  - pytest
