language: python
python:
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"

# env variables
env:
  global:
    secure: "Tl17DYChaDSOLQ7Ci7D30NqNT3ylckO9TBHoxafQ0bO7CKPdLttWJ8XpUGZNinxiWIGAsfnIaG1x12lMIfgimdhH8cF8qnyQELEeA73BQ5jxQzWEk/jQu16EoQxTK1LpFCub7kxC+nvT/N/efS8McK9sMpFAoAdu2Tp+RPhD2/8xkM5inPFphkNq3HCyGwktyYe00iP7dFhU2hWyTBo+4knzLWy55gOMJP320fK224bY+NbrvRQJBLW18a4iH6BsQfKGrybCRo2HnOwdvL/bZ5B/6w81EmIbs+kG02oAGO+MlOTc99QQSyp7I9Sc0PmjkOI3bGaoso01/vNvKgwD2tl1DvNzs7lySNGT8nWnn2dTsioTYTQOKxBjvMvFj/4eJo/YGEFmG9FEdGk8MOGcZoiQa0ZgzMxdTiTmhGMo6aej9avtRZPmlZ6Jc5sCntlTMjMPGwfKbaPpaLa4TYlvx7tUVPPPZa1VWhsn+DGJgMjce2A3ZDOMlTUONUiqpiLqYw5lQu5jRzMUMaINLDRKLi7CcI95XE6atPoTlkp9rvGxOFyejeA6munggDRD5koVuPzajSpbxXozgrBtC/JCbdkWEAqqs5CEshOdrsJhZTB7XIk7CtR1wzMJimw9enGa0O2OuOtJalyWnyr5bOVaPwpJ/H2y0Ft/zYyAGbq2FDY="

# command to run tests
script:
  - export SAS_TOKEN=$SAS_TOKEN
  - pytest
